services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SA_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}" ]
      interval: 10s
      retries: 20
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - projectnet

  backend:
    image: andrew77771/forum-test-task.be:latest
    build:
      context: ./ForumTestTask.BE
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=postgres;Password=${SA_PASSWORD};
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    volumes:
      - ./ForumTestTask.BE/wwwroot/uploads:/app/wwwroot/uploads
    networks:
      - projectnet
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: andrew77771/forum-test-task.fe:latest
    build:
      context: ./ForumTestTask.FE
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:5000
    volumes:
      - ./ForumTestTask.FE/certs:/etc/nginx/certs:ro
    networks:
      - projectnet
    depends_on:
      backend:
        condition: service_started

volumes:
  pg_data:


networks:
  projectnet:
